stroim/products/urls.py
from django.urls import path

from .import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('products_list', views.products_list, name='products_list'),
    path('product/<int:product_id>/', views.products_detail, name='products_detail'),
    path('product/<int:product_id>/comment/', views.add_comment, name='add_comment'),
    path('product/<int:product_id>/comment-form/', views.comment_form, name='comment_form'),
    path('category_list/<int:category_id>/', views.category_list, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('product/<int:product_id>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('product/<int:product_id>/remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('product/<int:product_id>/remove_from_cart_profile/', views.remove_from_cart_profile, name='remove_from_cart_profile'),
    path('search/', views.search_view, name='search'),
]

stroim/stroim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

stroim/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views
app_name = 'users'

urlpatterns = [
    path(
      'logout/',
      # Прямо в описании обработчика укажем шаблон, 
      # который должен применяться для отображения возвращаемой страницы.
      # Да, во view-классах так можно! Как их не полюбить.
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
] 

stroim/templates/includes/footer.html
<h4 class="footer-author">Я х ОПТИМУС ПРАЙМ</h4>
<p class="footer-cop">© 2024 Copyright <span style="color:rgb(12, 20, 240)">Строй</span>Балт</p>

stroim/templates/includes/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<div class='img-logo'>
  <a href="{% url 'products:index' %}">
  <img class="logo-scale" src={% static 'img/logo.png' %} width="90" height="85" alt="Логотип сайт">
  </a>
</div>
<a class='logo' href="{% url 'products:index' %}"><h1>КомфортСтрой</h1></a>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
<form class='poisk' action="/search" method="GET">
  <input type="search" name="query" placeholder="Поиск по названию товара"> 
  <i class="fa fa-search"></i>
</form>
<nav class="catalog">
  <ul>
    <li class="text-catalog"> <a href="#">Каталог</a>
      <ul>
        <li><a href="{% url 'products:category_list' 1 %}">Инструменты</a></li>
        <li><a href="{% url 'products:category_list' 2 %}">Краска</a></li>
        <li><a href="{% url 'products:category_list' 3 %}">Электротовары</a></li>
        <li><a href="{% url 'products:category_list' 4 %}">Болты</a></li>
        <li><a href="{% url 'products:category_list' 5 %}">Всё для сада</a></li>
        <li><a href="{% url 'products:category_list' 6 %}">Обои</a></li>
      </ul> 
    </li>
  </ul>
</nav>
{% if user.is_authenticated %}
<div class="auth auth-fix"><a href="{% url 'products:profile' user.username %}"> {{ user.username }}</a>
</div>
<a href="{% url 'products:profile' user.username %}">
<img style="margin-right: 40px;" class="img-logo" src="{% static 'img/profile.png' %}" width="60" height="50" alt='Иконка профиля'>
</a>
{% else %}
<div style="border-right: 2px black solid;" class="auth auth-fix" ><a href="{% url 'users:login' %}">Войти</a></div>
<div class="auth"><a href="{% url 'users:signup' %}">Регистрация</a></div>
{% endif %}

stroim/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <div class="pagination-container">
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
  </div>
{% endif %}