stroim/products/urls.py
from django.urls import path

from .import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('products_list', views.products_list, name='products_list'),
    path('product/<int:product_id>/', views.products_detail, name='products_detail'),
    path('product/<int:product_id>/comment/', views.add_comment, name='add_comment'),
    path('product/<int:product_id>/comment-form/', views.comment_form, name='comment_form'),
    path('category_list/<int:category_id>/', views.category_list, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('product/<int:product_id>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('product/<int:product_id>/remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('product/<int:product_id>/remove_from_cart_profile/', views.remove_from_cart_profile, name='remove_from_cart_profile'),
    path('search/', views.search_view, name='search'),
]

stroim/stroim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

stroim/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views
app_name = 'users'

urlpatterns = [
    path(
      'logout/',
      # Прямо в описании обработчика укажем шаблон, 
      # который должен применяться для отображения возвращаемой страницы.
      # Да, во view-классах так можно! Как их не полюбить.
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
] 

stroim/products/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import User


class Category(models.Model):
    name = models.TextField()
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.TextField(max_length=50)
    cost = models.PositiveIntegerField()
    description = models.TextField(max_length=500)
    image = models.ImageField(
        'Картинка',
        upload_to='products/',
        blank=True
    )
    amount = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class ShoppingCart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='shopping_cart_user')
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='shopping_cart_product')

    def __str__(self):
        return f'{self.user} добавил "{self.product}" в список покупок'


class Comment(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='comments')

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',)

    text = models.TextField(
        max_length=500)

    created = models.DateTimeField(
        verbose_name='Дата коммента',
        auto_now_add=True,)
    
    def __str__(self):
        return self.text

stroim/products/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        error_messages = {
            'text': {
                'required': "Пожалуйста, напишите комментарий.",
            }
        }

stroim/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages  # Импортируем messages для вывода сообщений об ошибках
from .models import Product, Category, ShoppingCart
from users.models import User
from .utils import paginate
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Q

PAGE_FOR_LIST = 8


def index(request):
    title = 'КомфортСтрой'
    context = {
        'title': title
    }
    return render(request, 'products/index.html', context)


def products_list(request):
    product = Product.objects.all()
    page_obj = paginate(request, product, PAGE_FOR_LIST)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'products/products_list.html', context)


def products_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    in_cart = False  # По умолчанию предполагаем, что товар не добавлен в корзину

    # Проверяем, аутентифицирован ли пользователь
    if request.user.is_authenticated:
        # Если пользователь аутентифицирован, проверяем, есть ли товар в корзине
        in_cart = ShoppingCart.objects.filter(user=request.user, product=product).exists()

    context = {
        'product': product,
        'in_cart': in_cart,
    }
    return render(request, 'products/products_detail.html', context)

@login_required
def add_comment(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = CommentForm(request.POST or None)
    
    if request.method == 'POST':
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.product = product
            comment.save()
            return redirect('products:products_detail', product_id=product_id)
        else:
            messages.error(request, 'Пожалуйста, напишите комментарий')  
    
    context = {
        'product': product,
        'form': form,
    }
    return render(request, 'products/comment_form.html', context)


def comment_form(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = CommentForm()
    context = {
        'product': product,
        'form': form,
    }
    return render(request, 'products/comment_form.html', context)


def category_list(request, category_id):
    category_name = Category.objects.get(id=category_id)
    product = Product.objects.filter(category=category_name)
    page_obj = paginate(request, product, PAGE_FOR_LIST)
    context = {
        'page_obj': page_obj,
        'category_name': category_name,
    }
    return render(request, 'products/category_list.html', context)


def profile(request, username):
    title = "Профиль"
    user = get_object_or_404(User, username=username)
    card = ShoppingCart.objects.filter(user=user.id)
    card_products = card.all()
    count_products = card_products.count()
    page_obj = paginate(request, card_products, PAGE_FOR_LIST)

    context =  {
        'page_obj': page_obj,
        'user': user,
        'title': title,
        'count_products': count_products,
    }
    return render(request, 'products/profile.html', context)


@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    ShoppingCart.objects.create(user=request.user, product=product)
    return redirect('products:products_detail', product_id=product_id)


@login_required
def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    ShoppingCart.objects.filter(user=request.user, product=product).delete()
    return redirect('products:products_detail', product_id=product_id)


@login_required
def remove_from_cart_profile(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    ShoppingCart.objects.filter(user=request.user, product=product).delete()
    return redirect('products:profile', username=request.user.username)


def search_view(request):
    query = request.GET.get('query')
    if query:
        # Выполните частичный поиск товаров по названию
        products = Product.objects.filter(Q(name__icontains=query))
        count_products = products.count()
    else:
        products = None
    return render(request, 'products/search_results.html', {'products': products,
                                                            'count_products': count_products})

stroim/templates/products/category_list.html
{% extends "base.html" %}
{% block title %}
{{category_name.name}}
{% endblock %}
{%block content%}
    <div class="card-text">{{category_name.name}}</div>
    <div class="container">
        <main class="lists">
            {% for products in page_obj %}
                    <div class="list">
                        <!-- Карточка товара -->
                        <!-- Верхняя часть -->
                        <div class="list__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="{% url 'products:products_detail' products.pk %}" class="list__image">
                                <img src="{{ products.image.url }}">
                            </a>
                        </div>
                        <!-- Нижняя часть -->
                        <div class="list__bottom">
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <div class="list__prices">
                                <div class="list__price">Цена: {{products.cost}} руб.</div>
                            </div>
                            <!-- Ссылка-название товара -->
                            <a href="{% url 'products:products_detail' products.pk %}" class="list__title">
                                {{products.name}}
                            </a>
                            <!-- Кнопка добавить в корзину -->
                        </div>
                    </div>
            {% endfor %}
        </main>
        <!-- Pagination -->
        {% include 'includes/paginator.html' %}
    </div>
{%endblock%}

stroim/templates/products/comment_form.html
{% extends 'base.html' %}
{% block title %}
Комментарий
{% endblock title %}
{% block content %}
    <div class='add_com'>
        <form class="decor" method="post" action="{% url 'products:add_comment' product.pk %}">
            {% csrf_token %}
            <div class="form-left-decoration"></div>
            <div class="form-right-decoration"></div>
            <div class="circle"></div>
            <div class="form-inner">
                <h3 class='h3_com'>Добавьте ваш комментарий:</h3>
                <!-- Добавляем атрибут maxlength с максимальной длиной из модели -->
                {% if form.errors %}
                    <div class="error-message">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
                <textarea class='text_com' name="text" placeholder="Сообщение..." rows="3" maxlength="{{ form.fields.text.max_length }}"></textarea>
                <input type="submit" value="Отправить" class="add-comment-btn">
            </div>
        </form>
    </div>
{% endblock %}

stroim/templates/products/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Главная
{% endblock title %}
{% block content %}
  <div class='over'>
    <div class="full-body">
              <section>
                <div class="text-info-left"> 
        <!-- Добро пожаловать в наш Строительный магазин! -->
                <h3 class="text-info-title"> Добро пожаловать в наш Строительный магазин! </h3>

              Мы предоставляем широкий ассортимент товаров для строительства, ремонта и обустройства вашего дома.
              В нашем магазине вы найдете высококачественные стройматериалы, инструменты, аксессуары и многое другое.<br><br>
              Будьте уверены, что в нашем магазине вы найдете все необходимое для успешного строительства и ремонта.
                </div>
              </div>
              </section>
              <div class="wrapper">
                <input type="radio" name="point" id="slide1" checked>
                <input type="radio" name="point" id="slide2">
                <input type="radio" name="point" id="slide3">
                <input type="radio" name="point" id="slide4">
                <input type="radio" name="point" id="slide5">
                <div class="slider">
                  <div class="slides slide1"></div>
                  <div class="slides slide2"></div>
                  <div class="slides slide3"></div>
                  <div class="slides slide4"></div>
                  <div class="slides slide5"></div>
                </div>	
                <div class="controls">
                  <label for="slide1"></label>
                  <label for="slide2"></label>
                  <label for="slide3"></label>
                  <label for="slide4"></label>
                  <label for="slide5"></label>
                </div>
              </div>

              <div class="card-text">Наши товары</div>
              <section>
                  <div class="cards">
                        <!-- Карточка товара 1-->
                        <div class="card">
                          <!-- Верхняя часть -->
                          <div class="card__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="#" class="card__image">
                              <img src="static/img/pin1.png">
                            </a>
                            <a href="{% url 'products:category_list' 1 %}" class='card_fon' >
                              <img src="static/img/1.png" alt="">
                            </a>
                          </div>
                          <!-- Нижняя часть -->
                          <div class="card__bottom">
                            <div class="create-line1"></div>
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <!-- Ссылка-название товара -->
                            <a href="#" class="card__title">
                              Инструменты
                            </a>
                            <!-- Кнопка добавить в корзину -->
                          </div>
                        </div>

                        <!-- Карточка товара 2-->
                        <div class="card">
                          <!-- Верхняя часть -->
                          <div class="card__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="#" class="card__image">
                              <img
                                src="static/img/pin2.png"
                              />
                              <a href="{% url 'products:category_list' 2 %}" class='card_fon' >
                                <img src="static/img/2.png" alt="">
                              </a>
                            </a>
                          </div>
                          <!-- Нижняя часть -->
                          <div class="card__bottom">
                            <div class="create-line2"></div>
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <!-- Ссылка-название товара -->
                            <a href="#" class="card__title">
                              Краска
                            </a>
                            <!-- Кнопка добавить в корзину -->
                          </div>
                        </div>

                        <!-- Карточка товара 3-->
                        <div class="card">
                          <!-- Верхняя часть -->
                          <div class="card__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="#" class="card__image">
                              <img
                                src="static/img/pin3.png"
                              />
                              <a href="{% url 'products:category_list' 3 %}" class='card_fon' >
                                <img src="static/img/3.png" alt="">
                              </a>
                            </a>
                          </div>
                          <!-- Нижняя часть -->
                          <div class="card__bottom">
                            <div class="create-line3"></div>
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <!-- Ссылка-название товара -->
                            <a href="#" class="card__title">
                              Электротовары
                            </a>
                            <!-- Кнопка добавить в корзину -->
                          </div>
                        </div>
                      
                                    <!-- Карточка товара 4-->
                        <div class="card">
                          <!-- Верхняя часть -->
                          <div class="card__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="#" class="card__image">
                              <img
                                src="static/img/pin4.png"
                              />
                              <a href="{% url 'products:category_list' 4 %}" class='card_fon' >
                                <img src="static/img/4.png" alt="">
                              </a>
                            </a>
                          </div>
                          <!-- Нижняя часть -->
                          <div class="card__bottom">
                            <div class="create-line4"></div>
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <!-- Ссылка-название товара -->
                            <a href="#" class="card__title">
                              Болты
                            </a>
                            <!-- Кнопка добавить в корзину -->
                          </div>
                        </div>

                                    <!-- Карточка товара 5-->
                        <div class="card5">
                          <div class="card">
                            <!-- Верхняя часть -->
                            <div class="card__top">
                              <!-- Изображение-ссылка товара -->
                              <a href="#" class="card__image">
                                <img
                                  src="static/img/pin5.png"
                                />
                                <a href="{% url 'products:category_list' 5 %}" class='card_fon' >
                                  <img src="static/img/5.png" alt="">
                                </a>
                              </a>
                            </div>
                            <!-- Нижняя часть -->
                            <div class="card__bottom">
                              <div class="create-line5"></div>
                              <!-- Цены на товар (с учетом скидки и без)-->
                              <!-- Ссылка-название товара -->
                              <a href="#" class="card__title">
                                Всё для сада
                              </a>
                              <!-- Кнопка добавить в корзину -->
                            </div>
                          </div>
                      </div>
                                    <!-- Карточка товара 6-->
                        <div class="card5">
                          <div class="card">
                            <!-- Верхняя часть -->
                            <div class="card__top">
                              <!-- Изображение-ссылка товара -->
                              <a href="#" class="card__image">
                                <img
                                  src="static/img/pin6.png"
                                />
                                <a href="{% url 'products:category_list' 6 %}" class='card_fon' >
                                  <img src="static/img/6.png" alt="">
                                </a>
                              </a>
                            </div>
                            <!-- Нижняя часть -->
                            <div class="card__bottom">
                              <div class="create-line6"></div>
                              <!-- Цены на товар (с учетом скидки и без)-->
                              <!-- Ссылка-название товара -->
                              <a href="#" class="card__title">
                                Обои
                              </a>
                              <!-- Кнопка добавить в корзину -->
                            </div>
                          </div>
                        </div>
                  </div>
                </section>
          <div style='text-decoration: underline; font-style: italic;' class="text_all"><a href="{% url 'products:products_list' %}">Просмотреть все товары..</a></div>

          </div>
      </div>    
    </div>
  </div>
{% endblock %}

stroim/templates/products/products_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class='pro'>
        <div class='pro_image'>
            <img src="{{ product.image.url }}">
        </div>
        <ol class='pro_list'>
            <li>
                <div class='pro_name'>
                    Название: {{ product.name }}
                </div>
            </li>
            <li>
                <div class='pro_cost'>
                    Цена: {{ product.cost }} руб.
                </div>
            </li>
            <li>
                <div class='pro_category'>
                    <a href="{% url 'products:category_list' 1 %}">
                        Категория: {{ product.category }}
                    </a>
                </div>
            </li>
            <li>
                <div class='pro_amount'>
                    Количество: {{ product.amount }}
                </div>
            </li>
            <li>
            {% if in_cart %}
                <a href="{% url 'products:remove_from_cart' product.id %}" class="list__remove">Убрать из корзины</a>
            {% else %}
                <a href="{% url 'products:add_to_cart' product.id %}" class="list__add">В корзину</a>
            {% endif %}
            </li>
        </ol>
    </div>
    <div class='pro_description'>
        <div class='opi'>Описание:</div> {{ product.description }}
    </div>

    <div class='com'><h1 style='font-style:italic'>КОММЕНТАРИИ</h1></div>

    <a href="{% url 'products:comment_form' product.pk %}">
        <button class="comment_add">Написать комментарий</button>
    </a>
    {% for comment in product.comments.all %}
        <div class='comments'>
            <div class='author-comment'>
                {{ forloop.counter }}. 
                {{ comment.author.username }}
            </div>
            <div class='pub_date_comment'>
                <p>{{ comment.created }}</p>
            </div>
            <div class='text-comment'>
                <p>{{ comment.text }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

stroim/templates/products/products_list.html
{% extends 'base.html' %}
{% block title %}
    Все товары
{% endblock %}
{% block content %}
    <div class="card-text">Наши товары</div>
    <div class="container">
        <main class="lists">
            {% for products in page_obj %}
                <div class="list">
                    <!-- Карточка товара -->
                    <!-- Верхняя часть -->
                    <div class="list__top">
                        <!-- Изображение-ссылка товара -->
                        <a href="{% url 'products:products_detail' products.pk %}" class="list__image">
                            <img src="{{ products.image.url }}">
                        </a>
                    </div>
                    <!-- Нижняя часть -->
                    <div class="list__bottom">
                        <!-- Цены на товар (с учетом скидки и без)-->
                        <div class="list__prices">
                            <div class="list__price">Цена: {{products.cost}} руб.</div>
                        </div>
                        <!-- Ссылка-название товара -->
                        <a href="{% url 'products:products_detail' products.pk %}" class="list__title">
                            {{products.name}}
                        </a>
                        <!-- Кнопка добавить в корзину -->
                    </div>
                </div>
            {% endfor %}
        </main>
        <!-- Pagination -->
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

stroim/templates/products/profile.html
{% extends 'base.html' %}
{% block title %}
    Профиль {{ user.username }}
{% endblock %}
{% block content %}
<div class="container">
    <div style="margin-bottom: 40px" class="user-profile">
        <h2> Профиль: {{ user.username }}</h2>
        
        <a style="color: black; text-decoration: underline" href="{% url 'users:logout' %}" class="logout-btn">
        <h3>Выйти из Профиля</h3></a>
    </div>
    {% if count_products == 0 %}
     <h1>Здесь отобразятся ваши товары добавленные в корзину</h1>
    {% else %}
        <div style="margin-bottom:30px">
            <h1>Добавленных товаров: {{count_products }}</h1>
        </div>
        <main class="lists">
            {% for cart in page_obj %}
            <div class="list">
                <!-- Карточка товара -->
                <!-- Верхняя часть -->
                <div class="list__top">
                    <!-- Изображение-ссылка товара -->
                    <a href="{% url 'products:products_detail' cart.product.pk %}" class="list__image">
                        <img src="{{ cart.product.image.url }}">
                    </a>
                </div>
                <!-- Нижняя часть -->
                <div class="list__bottom">
                    <!-- Цены на товар (с учетом скидки и без)-->
                    <div class="list__prices">
                        <div class="list__price">Цена: {{cart.product.cost}} руб.</div>
                    </div>
                    <!-- Ссылка-название товара -->
                    <a href="{% url 'products:products_detail' cart.product.pk %}" class="list__title">
                        {{cart.product.name}}
                    </a>
                    <!-- Кнопка удалить из корзины -->
                    <a href="{% url 'products:remove_from_cart_profile' cart.product.pk %}" class="list__remove">Убрать из корзины</a>
                </div>
            </div>
            {% endfor %}
        </main>
    {% endif %}
    <!-- Pagination -->
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}

stroim/templates/products/search_results.html
{% extends 'base.html' %}
{% block content %}
    {% if count_products == 0 %}
        <div class="card-text">Товары не найдены</div>
    {% else %}
        <div class="card-text">Найденные Товары: {{ count_products }}</div>
        <div class="container">
            <main class="lists">
                {% for product in products %}
                    <div class="list">
                        <!-- Карточка товара -->
                        <!-- Верхняя часть -->
                        <div class="list__top">
                            <!-- Изображение-ссылка товара -->
                            <a href="{% url 'products:products_detail' product.pk %}" class="list__image">
                                <img src="{{ product.image.url }}">
                            </a>
                        </div>
                        <!-- Нижняя часть -->
                        <div class="list__bottom">
                            <!-- Цены на товар (с учетом скидки и без)-->
                            <div class="list__prices">
                                <div class="list__price">Цена: {{product.cost}} руб.</div>
                            </div>
                            <!-- Ссылка-название товара -->
                            <a href="{% url 'products:products_detail' product.pk %}" class="list__title">
                                {{product.name}}
                            </a>
                            <!-- Кнопка добавить в корзину -->
                        </div>
                    </div>
                {% endfor %}
            </main>
    {% endif %}
        <!-- Pagination -->
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}